- name: Installing hyprland dependencies
  become: true
  community.general.pacman:
      update_cache: true
      state: present
      name:
          # aquamarine
          - wayland
          - wayland-protocols
          - hwdata
          - systemd-libs
          - mesa
          - seatd
          - pugixml
          - libdrm
          - libglvnd
          - libinput
          # hyprcursor
          - libzip
          - librsvg
          # hyprgraphics
          - libjpeg
          - libwebp
          - file
          - libspng
          - libjxl
          # hyprland
          - xorg-xwayland
          - pixman
          - cpio
          - cairo
          - pango
          # - glaze
          - tomlplusplus
          - re2
          - xcb-proto
          - xcb-util
          - xcb-util-keysyms
          - xcb-util-wm
          - xcb-util-errors
          - libxcb
          - libliftoff
          - libdisplay-info
          - libx11
          - libxfixes
          - libxcomposite
          - libxrender
          - libxcursor
          - libxkbcommon
          # hyprqt
          - qt6-wayland
          - qt5-wayland
          # xdg-desktop-portal-hyprland
          - pipewire
          - sdbus-cpp
          # hyprpolkit
          - polkit-qt6
          # hyprlock
          - pam
  tags:
      - hyprland
      - hyprwm

- name: Preparing to install hyprwm
  ansible.builtin.include_tasks: ./yaml/includes/build_hyprland.yaml
  vars:
      hypr_name: "{{ item.repo.split('/')[1] }}"
      hypr_repo: 'https://github.com/{{ item.repo }}.git'
      hypr_dest: '{{ DOTFILES_CACHE_DIR }}/hyprwm/{{ item.dest }}'
      hypr_version: '{{ item.version }}'
      hypr_tags: "{{ [item.tags] + ['hyprland', 'hyprwm'] }}"
  loop:
      - {
            repo: hyprwm/hyprutils,
            dest: hyprutils,
            version: '{{ HYPRUTILS_VERSION }}',
            tags: 'hyprutils',
        }
      - {
            repo: hyprwm/hyprlang,
            dest: hyprlang,
            version: '{{ HYPRLANG_VERSION }}',
            tags: hyprlang,
        }
      - {
            repo: hyprwm/hyprwayland-scanner,
            dest: hyprscanner,
            version: '{{ HYPRWAYLAND_SCANNER_VERSION }}',
            tags: hyprwaylandscanner,
        }
      - {
            repo: hyprwm/aquamarine,
            dest: aqumarine,
            version: '{{ AQUAMARINE_VERSION }}',
            tags: aquamarine,
        }
      - {
            repo: hyprwm/hyprgraphics,
            dest: hyprgraphics,
            version: '{{ HYPRGRAPHICS_VERSION }}',
            tags: hyprgraphics,
        }
      - {
            repo: hyprwm/hyprcursor,
            dest: hyprcursor,
            version: '{{ HYPRCURSOR_VERSION }}',
            tags: hyprcursor,
        }
      - {
            repo: hyprwm/Hyprland,
            dest: hyprland,
            version: '{{ HYPRLAND_VERSION }}',
            tags: hyprland,
        }
      - {
            repo: hyprwm/hyprland-qtutils,
            dest: hyprqtutils,
            version: '{{ HYPRQT_UTILS_VERSION }}',
            tags: hyprqtutils,
        }
      - {
            repo: hyprwm/hyprland-qt-support,
            dest: hyprqtsupport,
            version: '{{ HYPRQT_SUPPORT_VERSION }}',
            tags: hyprqtsupport,
        }
      - {
            repo: hyprwm/hyprpolkitagent,
            dest: hyprpolkit,
            version: '{{ HYPRPOLKIT_VERSION }}',
            tags: hyprpolkit,
        }
      - {
            repo: hyprwm/xdg-desktop-portal-hyprland,
            dest: hyprportal,
            version: '{{ XDG_PORTAL_HYPRLAND_VERSION }}',
            tags: hyprportal,
        }
      - {
            repo: hyprwm/hyprpaper,
            dest: hyprpaper,
            version: '{{ HYPRPAPER_VERSION }}',
            tags: hyprpaper,
        }
      - {
            repo: hyprwm/hypridle,
            dest: hypridle,
            version: '{{ HYPRIDLE_VERSION }}',
            tags: hypridle,
        }
      - {
            repo: hyprwm/hyprlock,
            dest: hyprlock,
            version: '{{ HYPRLOCK_VERSION }}',
            tags: hyprlock,
        }
      - {
            repo: hyprwm/hyprpicker,
            dest: hyprpicker,
            version: '{{ HYPRPICKER_VERSION }}',
            tags: hyprpicker,
        }
  loop_control:
      label: "{{ item.repo.split('/')[1] }}"
  tags:
      - hyprland
      - hyprwm

- name: Enabling hyprwm application service using systemd
  ansible.builtin.systemd_service:
      name: '{{ item.name }}'
      scope: '{{ item.scope }}'
      state: '{{ item.state | default(omit) }}'
      enabled: true
      daemon_reload: true
  loop:
      - {name: hyprpolkitagent, scope: user}
      - {name: hypridle, scope: user}
      - {name: hyprpaper, scope: user}
  tags:
      - hyprland
      - hyprwm
