- name: Installing hyprwm additional
  become: true
  community.general.pacman:
      update_cache: true
      state: present
      name:
          - thunar
          - ristretto
          - mousepad
          - okular
          - file-roller
          - wl-clipboard
          - cliphist
          - network-manager-applet
          - nm-connection-editor
          - pavucontrol
          - socat
          - thunar-archive-plugin
          - gvfs
          - gvfs-mtp
          - ffmpegthumbnailer
          - tumbler
          - webp-pixbuf-loader
          - mpv-mpris
          - xdg-user-dirs
  tags: hyprwm

- name: Bookmarking xdg-user-dirs folders
  ansible.builtin.lineinfile:
      path: '{{ CONFIG_DIR }}/gtk-3.0/bookmarks'
      line: 'file://{{ HOME_DIR }}/{{ item }}'
      regexp: 'file://{{ HOME_DIR }}/{{ item }}'
      state: present
      create: true
  loop:
      - Documents
      - Downloads
      - Music
      - Pictures
      - Public
      - Templates
      - Videos
  tags: hyprwm
