- name: Installing rofi dependencies
  become: true
  community.general.pacman:
      update_cache: true
      state: present
      name:
          - check
          - wayland
          - wtype
          - librsvg
          - libxdg-basedir
          - libxkbcommon-x11
          - startup-notification
          - xcb-util-cursor
          - xcb-util-keysyms
          - xcb-util-wm
          - xcb-util-xrm
          - libqalculate
  tags:
      - rofi
      - hyprwm

- name: Downloading rofi source
  ansible.builtin.git:
      repo: 'https://github.com/{{ item.repo }}.git'
      dest: '{{ DOTFILES_CACHE_DIR }}/{{ item.dest }}'
      version: '{{ item.version }}'
      depth: 1
      recursive: true
      update: false
  loop:
      - {repo: 'lbonn/rofi', dest: 'rofi', version: '{{ ROFI_VERSION }}'}
      - {
            repo: 'svenstaro/rofi-calc',
            dest: 'rofi-calc',
            version: '{{ ROFI_CALC_VERSION }}',
        }
      - {
            repo: 'mange/rofi-emoji',
            dest: 'rofi-emoji',
            version: '{{ ROFI_EMOJI_VERSION }}',
        }
  tags:
      - rofi
      - hyprwm

- name: Compiling rofi wayland
  ansible.builtin.shell: |
      meson setup build \
          -Dwayland=enabled \
          --prefix=/usr/local
  args:
      chdir: '{{ DOTFILES_CACHE_DIR }}/rofi'
  tags:
      - rofi
      - hyprwm

- name: Installing rofi wayland
  become: true
  ansible.builtin.shell: meson install -C build
  args:
      chdir: '{{ DOTFILES_CACHE_DIR }}/rofi'
  tags:
      - rofi
      - hyprwm

- name: Compiling rofi library
  ansible.builtin.shell: |
      autoreconf -i
      ./configure --prefix=/usr/local
      make
  loop: [rofi-calc, rofi-emoji]
  args:
      chdir: '{{ DOTFILES_CACHE_DIR }}/{{ item }}'
  environment:
      PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:{{ ansible_env.PKG_CONFIG_PATH | default('') }}"
  tags:
      - rofi
      - hyprwm

- name: Installing rofi library
  become: true
  ansible.builtin.shell: |
      cd {{ DOTFILES_CACHE_DIR }}/{{ item }}
      make install
  loop: [rofi-calc, rofi-emoji]
  args:
      chdir: '{{ DOTFILES_CACHE_DIR }}/{{ item }}'
  tags:
      - rofi
      - hyprwm
