- name: Installing uwsm dependencies
  become: true
  community.general.pacman:
      update_cache: true
      state: present
      name:
          - python-dbus
          - python-pyxdg
          - scdoc
          - libnewt
  tags:
      - uwsm
      - hyprwm

- name: Downloading uwsm source
  ansible.builtin.git:
      repo: https://github.com/Vladimir-csp/uwsm.git
      dest: '{{ DOTFILES_CACHE_DIR }}/uwsm'
      version: '{{ UWSM_VERSION }}'
      depth: 1
      recursive: true
      update: false
  tags:
      - uwsm
      - hyprwm

- name: Compiling uwsm
  ansible.builtin.shell: |
      meson setup build --prefix=/usr/local \
                  -Duuctl=enabled \
                  -Dfumon=enabled \
                  -Duwsm-app=enabled

      meson compile -C build
  args:
      chdir: '{{ DOTFILES_CACHE_DIR }}/uwsm'
  tags:
      - uwsm
      - hyprwm

- name: Installing uwsm
  become: true
  ansible.builtin.shell: meson install -C build
  args:
      chdir: '{{ DOTFILES_CACHE_DIR }}/uwsm'
  tags:
      - uwsm
      - hyprwm
