- hosts: localhost
  gather_facts: true
  vars_files:
      - ./yaml/variables.yaml
      - ./yaml/versions.yaml
  pre_tasks:
      - import_tasks: ./yaml/tasks/directory.yaml
      - import_tasks: ./yaml/tasks/personal.yaml
      - import_tasks: ./yaml/tasks/tools.yaml
  tasks:
      - import_tasks: ./yaml/tasks/dotfiles.yaml
      - import_tasks: ./yaml/tasks/nodejs.yaml
      - import_tasks: ./yaml/tasks/php.yaml
      - import_tasks: ./yaml/tasks/golang.yaml
      - import_tasks: ./yaml/tasks/rust.yaml
      - import_tasks: ./yaml/tasks/packages.yaml
      - import_tasks: ./yaml/tasks/browser.yaml
      - import_tasks: ./yaml/tasks/nerdfonts.yaml
      - import_tasks: ./yaml/tasks/neovim.yaml
      - import_tasks: ./yaml/tasks/git.yaml
      - import_tasks: ./yaml/tasks/flameshot.yaml

      - import_tasks: ./yaml/tasks/hyprwm/pipewire.yaml
      - import_tasks: ./yaml/tasks/hyprwm/bluetooth.yaml
      - import_tasks: ./yaml/tasks/hyprwm/hyprland.git.yaml
      - import_tasks: ./yaml/tasks/hyprwm/uwsm.yaml
      - import_tasks: ./yaml/tasks/hyprwm/packages.yaml
      - import_tasks: ./yaml/tasks/hyprwm/flatpak.yaml
      - import_tasks: ./yaml/tasks/hyprwm/fcitx.yaml
      - import_tasks: ./yaml/tasks/hyprwm/udiskie.yaml
      - import_tasks: ./yaml/tasks/hyprwm/tlp.yaml
      - import_tasks: ./yaml/tasks/hyprwm/rofi.yaml
      - import_tasks: ./yaml/tasks/hyprwm/swaync.yaml
      - import_tasks: ./yaml/tasks/hyprwm/waybar.yaml
      - import_tasks: ./yaml/tasks/hyprwm/theme.yaml
