- name: Installing fcitx
  become: true
  community.general.pacman:
      update_cache: true
      state: present
      name:
          - fcitx5
          - fcitx5-qt
          - fcitx5-gtk
          - fcitx5-mozc
          - fcitx5-hangul
          - fcitx5-configtool
  tags: fcitx

- name: Downloading fcitx theme
  ansible.builtin.git:
      repo: https://github.com/catppuccin/fcitx5.git
      dest: '{{ DOTFILES_CACHE_DIR }}/fcitx-theme'
      depth: 1
      recursive: true
      update: false
  tags: fcitx

- name: Installing fcitx catppuccin theme
  ansible.builtin.copy:
      src: '{{ DOTFILES_CACHE_DIR }}/fcitx-theme/src/catppuccin-mocha-mauve'
      dest: '{{ DATA_DIR }}/share/fcitx5/themes/'
  tags: fcitx
