- name: Installing flatpak
  become: true
  community.general.pacman:
      update_cache: true
      state: present
      name: flatpak
  tags: flatpak

- name: Adding flatpak repository remote
  community.general.flatpak_remote:
      name: flathub
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      state: present
      method: user
  tags: flatpak

- name: Installing app using flatpak
  community.general.flatpak:
      method: user
      state: present
      remote: flathub
      name: '{{ item }}'
  loop:
      - com.github.tchx84.Flatseal
      - md.obsidian.Obsidian
      - org.chromium.Chromium
  tags: flatpak

- name: Configuring flatpak
  ansible.builtin.shell: |
      flatpak override --user --allow=bluetooth

      flatpak override --user --device=dri
      flatpak override --user --device=input
      flatpak override --user --device=shm
      flatpak override --user --device=all

      flatpak override --user --socket=x11
      flatpak override --user --socket=wayland
      flatpak override --user --socket=pulseaudio
      flatpak override --user --socket=session-bus
      flatpak override --user --socket=system-bus
      flatpak override --user --socket=ssh-auth
      flatpak override --user --socket=inherit-wayland-socket

      flatpak override --user --filesystem=home
      flatpak override --user --filesystem=xdg-config/gtk-3.0:ro
      flatpak override --user --filesystem=xdg-config/gtk-4.0:ro
      flatpak override --user --filesystem=xdg-config/Kvantum:ro
      flatpak override --user --filesystem=xdg-data/themes:ro
      flatpak override --user --filesystem=xdg-data/fonts:ro

      flatpak override --user --env=QT_STYLE_OVERRIDE=kvantum
      flatpak override --user --env=QT_QPA_PLATFORM="wayland;xcb"
      flatpak override --user --env=ELECTRON_OZONE_PLATFORM_HINT=auto
      flatpak override --user --env=GTK_THEME="{{ GTK_THEME }}"
  tags: flatpak
