- name: Installing hyprland dependencies
  become: true
  community.general.pacman:
      update_cache: true
      state: present
      name:
          - hyprland
          - xdg-desktop-portal-hyprland
          - hyprpolkitagent
          - hypridle
          - hyprlock
          - hyprpaper
          - hyprpicker
          - uwsm
          - rofi-wayland
          - swaync
          - waybar

          - thunar
          - ristretto
          - mousepad
          - okular
          - file-roller
          - network-manager-applet
          - nm-connection-editor
          - pavucontrol
          - socat
          - thunar-archive-plugin
          - gvfs
          - gvfs-mtp
          - ffmpegthumbnailer
          - tumbler
          - webp-pixbuf-loader
          - mpv-mpris
          - xdg-user-dirs

          - wtype
          - libqalculate
          - wl-clipboard
          - cliphist

          - gtk3
          - gtk4
          - qt5ct
          - qt6ct
          - kvantum
          - kvantum-qt5
          - nwg-look
          - sassc
          - adwaita-cursors
          - inter-font
          - noto-fonts-emoji
          - noto-fonts-cjk
          - otf-font-awesome
          - ttf-dejavu
          - ttf-liberation
  tags: hyprwm

- name: Downloading hyprwm additional package source
  ansible.builtin.git:
      repo: 'https://github.com/{{ item.repo }}.git'
      dest: '{{ DOTFILES_CACHE_DIR }}/{{ item.dest }}'
      version: '{{ item.version }}'
      depth: 1
      recursive: true
      update: false
  loop:
      - {repo: 'svenstaro/rofi-calc', dest: 'rofi-calc', version: v2.3.0}
      - {repo: 'mange/rofi-emoji', dest: 'rofi-emoji', version: v4.10}
      - {
            repo: 'vinceliuice/Colloid-gtk-theme',
            dest: 'gtk-theme',
            version: 2024-11-16,
        }
      - {
            repo: 'PapirusDevelopmentTeam/papirus-icon-theme',
            dest: 'icon-pack',
            version: 20250201,
        }
  tags: hyprwm

- name: Compiling rofi plugins
  ansible.builtin.shell: |
      autoreconf -i
      ./configure --prefix=/usr
      make
  loop: [rofi-calc, rofi-emoji]
  args:
      chdir: '{{ DOTFILES_CACHE_DIR }}/{{ item }}'
  tags:
      - rofi
      - hyprwm

- name: Installing rofi plugins
  become: true
  ansible.builtin.shell: |
      cd {{ DOTFILES_CACHE_DIR }}/{{ item }}
      make install
  loop: [rofi-calc, rofi-emoji]
  args:
      chdir: '{{ DOTFILES_CACHE_DIR }}/{{ item }}'
  tags:
      - rofi
      - hyprwm

- name: Creating theme directory
  ansible.builtin.file:
      dest: '{{ item }}'
      state: directory
  loop:
      - '{{ DATA_DIR }}/share/themes'
      - '{{ DATA_DIR }}/share/icons'
      - '{{ CONFIG_DIR }}/gtk-4.0'
      - '{{ CONFIG_DIR }}/gtk-3.0'
  tags:
      - theme
      - hyprwm

- name: Installing gtk theme and icons
  ansible.builtin.shell: |
      cd {{ DOTFILES_CACHE_DIR }}/gtk-theme
      make install PREFIX={{ DATA_DIR }} 

      cd {{ DOTFILES_CACHE_DIR }}/icon-pack
      ./install.sh --dest {{ DATA_DIR }}/share/themes \
                   --theme purple \
                   --color dark \
                   --size compact \
                   --libadwaita \
                   --tweaks catppuccin black
  args:
      chdir: ''
  tags:
      - theme
      - hyprwm

- name: Applying gtk theme
  ansible.builtin.shell: |
      gsettings set org.gnome.desktop.interface gtk-theme '{{ GTK_THEME }}'
      gsettings set org.gnome.desktop.wm.preferences theme '{{ GTK_THEME }}'
      gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
      gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
      gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'
      gsettings set org.gnome.desktop.interface font-name 'Inter Display Semi-Bold 14'
  tags: hyprwm

- name: Creating xdg-user-dirs bookmark
  ansible.builtin.lineinfile:
      path: '{{ CONFIG_DIR }}/gtk-3.0/bookmarks'
      line: 'file://{{ HOME_DIR }}/{{ item }}'
      regexp: 'file://{{ HOME_DIR }}/{{ item }}'
      state: present
      create: true
  loop:
      - Documents
      - Downloads
      - Music
      - Pictures
      - Public
      - Templates
      - Videos
  tags: hyprwm

- name: Enabling hyprwm application service using systemd
  ansible.builtin.systemd_service:
      name: '{{ item.name }}'
      scope: '{{ item.scope }}'
      state: '{{ item.state | default(omit) }}'
      enabled: true
      daemon_reload: true
  loop:
      - {name: hyprpolkitagent, scope: user}
      - {name: hypridle, scope: user}
      - {name: hyprpaper, scope: user}
  tags: hyprwm
