- name: Installing hyprland packages
  become: true
  community.general.pacman:
      update_cache: true
      state: present
      name:
          - hyprland
          - xdg-desktop-portal-hyprland
          - hyprpolkitagent
          - hypridle
          - hyprlock
          - hyprpaper
          - hyprpicker
          - uwsm
          - rofi-wayland
          - swaync
          - waybar

          - thunar
          - ristretto
          - mousepad
          - okular
          - file-roller
          - network-manager-applet
          - nm-connection-editor
          - pavucontrol
          - socat
          - thunar-archive-plugin
          - gvfs
          - gvfs-mtp
          - ffmpegthumbnailer
          - tumbler
          - webp-pixbuf-loader
          - mpv-mpris
          - xdg-user-dirs

          - wtype
          - libqalculate
          - wl-clipboard
          - cliphist
  tags: hyprwm

- name: Downloading hyprwm additional package source
  ansible.builtin.git:
      repo: 'https://github.com/{{ item.repo }}.git'
      dest: '{{ DOTFILES_CACHE_DIR }}/{{ item.dest }}'
      version: '{{ item.version }}'
      depth: 1
      recursive: true
      update: false
  loop:
      - {repo: 'svenstaro/rofi-calc', dest: 'rofi-calc', version: v2.3.0}
      - {repo: 'mange/rofi-emoji', dest: 'rofi-emoji', version: v4.1.0}
  tags: hyprwm

- name: Compiling rofi plugins
  ansible.builtin.shell: |
      autoreconf -i
      ./configure --prefix=/usr/local
      make
  loop: [rofi-calc, rofi-emoji]
  args:
      chdir: '{{ DOTFILES_CACHE_DIR }}/{{ item }}'
  environment:
      PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig: {{ ansible_env.PKG_CONFIG_PATH | default('') }}"
  tags: hyprwm

- name: Installing rofi plugins
  become: true
  ansible.builtin.shell: |
      cd {{ DOTFILES_CACHE_DIR }}/{{ item }}
      make install
  loop: [rofi-calc, rofi-emoji]
  args:
      chdir: '{{ DOTFILES_CACHE_DIR }}/{{ item }}'
  tags: hyprwm

- name: Enabling hyprwm application service using systemd
  ansible.builtin.systemd_service:
      name: '{{ item.name }}'
      scope: '{{ item.scope }}'
      state: '{{ item.state | default(omit) }}'
      enabled: true
      daemon_reload: true
  loop:
      - {name: hyprpolkitagent, scope: user}
      - {name: hypridle, scope: user}
      - {name: hyprpaper, scope: user}
  tags: hyprwm
