- name: Installing packages
  become: true
  community.general.pacman:
      update_cache: true
      state: present
      name:
          - kitty
          - mpv
          - android-file-transfer

          - zsh
          - tmux
          - btop
          - fastfetch
          - bat
          - eza
          - fzf
          - trash-cli
          - less
          - tldr
          - man
          - fd
          - jq
          - ripgrep
          - awk
  tags: packages

- name: Changing default shell to zsh
  become: true
  ansible.builtin.user:
      shell: '/usr/bin/zsh'
      name: '{{ ansible_user_id }}'
  tags: packages

- name: Configuring shell environment
  ansible.builtin.shell: |
      zsh -c "source {{ HOME_DIR }}/.zshrc"

      if command -v bat &>/dev/null;then
          bat cache --build
      fi

      if command -v batcat &>/dev/null;then
          batcat cache --build
      fi
  tags: packages

- name: Creating xdg-user-dirs bookmark
  ansible.builtin.lineinfile:
      path: '{{ CONFIG_DIR }}/gtk-3.0/bookmarks'
      line: 'file://{{ HOME_DIR }}/{{ item }}'
      regexp: 'file://{{ HOME_DIR }}/{{ item }}'
      state: present
      create: true
  loop:
      - Documents
      - Downloads
      - Music
      - Pictures
      - Public
      - Templates
      - Videos
  tags: packages
