- name: Copying ssh keys
  ansible.builtin.copy:
      src: '{{ playbook_dir }}/.ssh/'
      dest: '{{ HOME_DIR }}/.ssh'
      mode: 0600
  tags:
      - ssh
      - personal

- name: Authorizing public ssh key
  ansible.posix.authorized_key:
      user: '{{ USER }}'
      key: "{{ lookup('file', item) }}"
      state: present
  loop: "{{ lookup('fileglob', '{{ HOME_DIR }}/.ssh/*.pub', wantlist=True) }}"
  tags:
      - ssh
      - personal

- name: Downloading personal repository
  ansible.builtin.git:
      repo: git@github.com:{{ USER_GITHUB }}/{{ item.repo }}.git
      dest: '{{ item.dest }}'
      depth: 1
      update: false
      recursive: true
      accept_hostkey: true
  loop:
      - {repo: Personal, dest: '{{ playbook_dir }}/Personal'}
      - {repo: Notes, dest: '{{ HOME_DIR }}/Documents/Notes'}
      - {repo: dotfiles, dest: '{{ playbook_dir }}/dotfiles'}
      - {repo: Nvimrc, dest: '{{ playbook_dir }}/dotfiles/common/.config/nvim'}
  tags: personal
