- name: Installing udiskie for Archlinux
  become: true
  community.general.pacman:
      update_cache: true
      state: present
      name: udiskie
  tags: udiskie

- name: Configuring udiskie mountpoint
  become: true
  ansible.builtin.lineinfile:
      path: '{{ item.path }}'
      line: '{{ item.line }}'
      regexp: '{{ item.regexp }}'
      state: present
      create: true
  loop:
      - {
            path: /etc/tmpfiles.d/media.conf,
            line: D /media 0755 root root 0 -,
            regexp: '^D\s*\/media.*root',
        }
      - {
            path: /etc/udev/rules.d/99-udisks2.rules,
            line: 'ENV{ID_FS_USAGE}=="filesystem|other|crypto", ENV{UDISKS_FILESYSTEM_SHARED}="1"',
            regexp: '^ENV{ID_FS_USAGE}==',
        }
  tags: udiskie

- name: Configuring udiskie mount options
  become: true
  ansible.builtin.ini_file:
      path: /etc/udisks2/mount_options.conf
      section: defaults
      option: '{{ item.option }}'
      value: '{{ item.value }}'
      state: present
      create: true
      no_extra_spaces: true
  loop:
      - {
            option: exfat_defaults,
            value: 'uid=$UID,gid=$GID,iocharset=utf8,errors=remount-ro,sync',
        }
      - {option: ntfs:ntfs3_defaults, value: 'uid=$UID,gid=$GID'}
  tags: udiskie
