- name: Installing common tools packages
  become: true
  community.general.pacman:
      update_cache: true
      state: present
      name:
          - openssh
          - base-devel
          - meson
          - ninja
          - make
          - cmake
          - extra-cmake-modules
          - ccache
          - curl
          - wget
          - tar
          - zip
          - unzip
          - unrar
          - p7zip
  tags: tools
